
---
- name: Install fail2ban
  package: name=fail2ban state=latest


- name: ensure fail2ban is installed
  yum: name=fail2ban state=latest
  notify:
    - restart fail2ban

- name: ensure fail2ban is configured
  template: src={{ item }}.j2 dest=/{{ item }}
  with_items:
    - etc/fail2ban/jail.local
    - etc/fail2ban/fail2ban.local
    - etc/fail2ban/filter.d/nginx-xmlrpc.conf
  notify:
    - restart fail2ban

- name: ensure fail2ban starts on a fresh reboot
  service: name=fail2ban state=started enabled=yes